name: CI-CD Apache (build en servidor)

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Validación mínima
        run: |
          test -f site/index.html
          test -f Dockerfile

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Despliegue por SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: "${{ secrets.DEPLOY_HOST }}"
          username: "${{ secrets.DEPLOY_USER }}"
          key: "${{ secrets.DEPLOY_SSH_KEY }}"

          script: |
            cd /srv/apache-cicd
            git pull origin main
            docker compose up -d --build
